export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="th">
      <body className="bg-[var(--color-bg-main)] text-[var(--color-text-main)] font-sans">{children}</body>
    </html>
  );
}
