export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <body className="bg-black text-white min-h-screen">{children}</body>
  )
}
