export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-black via-gray-900 to-white text-white min-h-screen">
        {/* Spinner overlay: ซ่อน spinner โดย default */}
        <div id="global-spinner" style={{display:'none'}}>
          <div className="spinner"></div>
          <div className="spinner-text">กำลังโหลด...</div>
        </div>
        {children}
      </body>
    </html>
  )
}
